registers:
  holding:
    1:
      name: State Power
      states:
        0: Battery First
        1: Solar First
        2: Grid First
      type: select
      icon: mdi:power-settings
    2:
      name: State Charge
      states:
        0: Solar First
        1: Solar and Grid
        2: Solar Only
      type: select
      icon: mdi:battery-charging-high
    7:
      name: PV Input Mode
      states:
        0: Independent
        1: Parallel
      type: sensor
      icon: mdi:engine
    8:
      name: AC Input Mode
      states:
        0: Appliance
        1: UPS
        2: Generator
      type: sensor
      icon: mdi:engine
    20:
      name: Overload Restart
      states:
        0: "Yes"
        1: "No"
        2: Switch to Grid
      type: select
      icon: mdi:restart
    21:
      name: Over Temperature Restart
      states:
        0: "Yes"
        1: "No"
      type: select
      icon: mdi:restart
    22:
      name: Buzzer
      states:
        0: "Off"
        1: "On"
      type: select
      icon: mdi:home-sound-in
    34:
      name: Max Charge Current
      data_type: int
      device_class: current
      unit_of_measurement: A
      type: sensor
    38:
      name: Max AC Charge Current
      data_type: int
      device_class: current
      unit_of_measurement: A
      type: sensor
    39:
      name: Battery Type
      states:
        0: AGM
        1: Flooded
        2: User Defined
        3: Lithium
        4: User Defined 2
      type: sensor
      icon: mdi:home-battery
  input:
    0:
      name: Inverter Status
      states:
        0: Standby
        1: Unknown
        2: Discharge
        3: Fault
        4: Flash
        5: PV Charge
        6: AC Charge
        7: Combine Charge
        8: Combine Charge and Bypass
        9: PV Charge and Bypass
        10: AC Charge and Bypass
        11: Bypass
        12: PV Charge and Discharge
      type: sensor
      icon: mdi:information
    1:
      name: PV Volts
      data_type: float
      math: a*0.1
      device_class: voltage
      unit_of_measurement: V
      type: sensor
    3:
      or: 4
      name: PV Power
      data_type: int
      math: a*0.1
      device_class: power
      unit_of_measurement: W
      type: sensor
    
    7:
      name: PV Charge Current
      data_type: float
      math: a*0.1
      device_class: power
      unit_of_measurement: A
      type: sensor
      
    9:
      or: 10
      name: Output Power
      data_type: int
      math: a*0.1
      device_class: power
      unit_of_measurement: W
      type: sensor
    12:
      name: Inverter Voltamps
      data_type: float
      math: a*0.001
      device_class: apparent_power
      type: sensor

    13:
      or: 14
      name: AC Charge Power
      data_type: int
      math: a*0.1
      device_class: power
      unit_of_measurement: W
      type: sensor

    17:
      name: Battery Volts
      data_type: float
      math: a*0.01
      device_class: voltage
      unit_of_measurement: V
      type: sensor
    18:
      name: Battery State Of Charge
      data_type: int
      device_class: battery
      unit_of_measurement: "%"
      type: sensor
    20:
      name: Grid Volts
      data_type: float
      math: a*0.1
      device_class: voltage
      unit_of_measurement: V
      type: sensor
    21:
      name: Grid Frequency
      data_type: int
      math: a*0.01
      device_class: frequency
      unit_of_measurement: Hz
      type: sensor
    22:
      name: Inverter Volts
      data_type: float
      math: a*0.1
      device_class: voltage
      unit_of_measurement: V
      type: sensor
    23:
      name: Inverter Frequency
      data_type: int
      math: a*0.01
      device_class: frequency
      unit_of_measurement: Hz
      type: sensor
    24:
      name: Output Volts
      data_type: float
      math: a*0.1
      device_class: voltage
      unit_of_measurement: V
      type: sensor

    25:
      name: Inverter Temp
      data_type: int
      math: a*0.1
      device_class: temperature
      unit_of_measurement: "°C"
      type: sensor
    26:
      name: DCDC Temp
      data_type: int
      math: a*0.1
      device_class: temperature
      unit_of_measurement: "°C"
      type: sensor
    27:
      name: Inverter Load
      data_type: int
      math: a*0.1
      unit_of_measurement: "%"
      type: sensor
      icon: mdi:tray-arrow-up

    34:
      name: Output Current
      data_type: float
      math: a*0.1
      device_class: current
      unit_of_measurement: A
      type: sensor

    35:
      name: Inverter Current
      data_type: float
      math: a*0.01
      device_class: current
      unit_of_measurement: A
      type: sensor

    36:
      name: AC Power
      or: 37
      data_type: int
      math: a*0.1
      device_class: energy
      unit_of_measurement: W
      type: sensor

    42:
      name: Fault Code
      data_type: int
      type: sensor

    43:
      name: Warning Code
      data_type: int
      type: sensor

    47:
      name: Constant Power OK
      states:
        0: Not OK
        1: OK
      type: sensor
      icon: mdi:information

    50:
      or: 51
      name: PV History Total
      data_type: float
      math: a*0.1
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      type: sensor

    58:
      or: 59
      name: Charge History Total
      data_type: float
      math: a*0.1
      add: 51
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      type: sensor

    60:
      or: 61
      name: Battery Output Today
      data_type: float
      math: a*0.1
      round: 0
      device_class: energy
      unit_of_measurement: kWh
      type: sensor

    62:
      or: 63
      name: Battery History Total
      data_type: float
      math: a*0.1
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      type: sensor

    66:
      or: 67
      name: AC History Total
      data_type: float
      math: a*0.1
      add: 59
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      type: sensor

    68:
      name: AC Charge Current
      data_type: float
      math: a*0.1
      device_class: current
      unit_of_measurement: A
      type: sensor

    73:
      or: 74
      name: Discharge Power
      data_type: int
      math: a*0.1
      device_class: power
      unit_of_measurement: W
      type: sensor

    77:
      signed: 78
      name: Battery Power
      data_type: int
      math: a*0.1
      device_class: power
      unit_of_measurement: W
      type: sensor      

    80:
      name: Battery Over Charge
      states:
        0: Not Over Charge
        1: Over Charge
      type: sensor
      icon: mdi:information
    
    81:
      name: MPPT Fan Speed
      data_type: int
      unit_of_measurement: "%"
      type: sensor
      icon: mdi:fan
    
    82:
      name: Inverter Fan Speed
      data_type: int
      unit_of_measurement: "%"
      type: sensor
      icon: mdi:fan

#    83:
#      name: Charge Current
#      type: float
#      math: a*0.1
#      round: 0
#      device_class: current
#      unit_of_measurement: A
#      type: sensor

transform:
  Grid Connected:
    condition: a>=100
    sources:
      - Grid Volts
    payload_on: "ON"
    payload_off: "OFF"
    type: binary_sensor
    icon: mdi:transmission-tower
  
  Battery Charge Power:
    data_type: int
    sources:
      - Battery Power
    device_class: power
    unit_of_measurement: W
    type: sensor
    valid_range: negative

  Battery Discharge Power:
    data_type: int
    sources:
      - Battery Power
    device_class: power
    unit_of_measurement: W
    type: sensor
    valid_range: positive

  Charge Power:
    math: a+b
    data_type: int
    sources:
      - AC Charge Power
      - PV Power
    device_class: power
    unit_of_measurement: W
    type: sensor  

#  Battery Power:
#    math: a-b
#    data_type: int
#    sources:
#      - Discharge Power
#      - Charge Power
#    device_class: power
#    unit_of_measurement: W
#    type: sensor

  Charge Current:
    math: a+b
    data_type: float
    sources:
      - AC Charge Current
      - PV Charge Current
    device_class: current
    unit_of_measurement: A
    type: sensor      

  Output Total:
    math: a+b+c
    data_type: float
    sources:
      - AC History Total
      - Battery History Total
      - PV History Total
    device_class: energy
    unit_of_measurement: kWh
    state_class: total_increasing
    type: sensor

  Output Combined:
    math: a+b
    data_type: int
    sources:
      - Output Power
      - Battery Charge Power
    device_class: power
    unit_of_measurement: W
    type: sensor